//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AirlineCountryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AirlineCountryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_Heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_TargetedCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_Flights" type="{}anc_FlightsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirlineCountryType", propOrder = { "hdlTitle", "stfHeading", "stfTargetedCountry", "ancFlights" })
public class AirlineCountryType {

	@XmlElement(name = "hdl_Title", required = true)
	protected String hdlTitle;
	@XmlElement(name = "stf_Heading", required = true)
	protected String stfHeading;
	@XmlElement(name = "stf_TargetedCountry", required = true)
	protected String stfTargetedCountry;
	@XmlElement(name = "anc_Flights", required = true)
	protected AncFlightsType ancFlights;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the hdlTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHdlTitle() {
		return hdlTitle;
	}

	/**
	 * Sets the value of the hdlTitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setHdlTitle(String value) {
		this.hdlTitle = value;
	}

	/**
	 * Gets the value of the stfHeading property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfHeading() {
		return stfHeading;
	}

	/**
	 * Sets the value of the stfHeading property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfHeading(String value) {
		this.stfHeading = value;
	}

	/**
	 * Gets the value of the stfTargetedCountry property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfTargetedCountry() {
		return stfTargetedCountry;
	}

	/**
	 * Sets the value of the stfTargetedCountry property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfTargetedCountry(String value) {
		this.stfTargetedCountry = value;
	}

	/**
	 * Gets the value of the ancFlights property.
	 * 
	 * @return possible object is {@link AncFlightsType }
	 * 
	 */
	public AncFlightsType getAncFlights() {
		return ancFlights;
	}

	/**
	 * Sets the value of the ancFlights property.
	 * 
	 * @param value allowed object is {@link AncFlightsType }
	 * 
	 */
	public void setAncFlights(AncFlightsType value) {
		this.ancFlights = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
