//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anc_ListItemType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="anc_ListItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txt_Teaser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_IsExternalSiteArticle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_TrackingTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_LinkLearnMore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_externalLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opt_isNewWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_TrackingEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_ExternalLinkTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="med_File" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anc_ListItemType", propOrder = { "url", "hdlTitle", "txtTeaser", "stfIsExternalSiteArticle",
	"stfTrackingTitle", "stfLinkLearnMore", "stfExternalLink", "optIsNewWindow", "stfTrackingEvent",
	"stfExternalLinkTitle", "medFile" })
public class AncListItemType {

	@XmlElement(required = true)
	protected String url;
	@XmlElement(name = "hdl_Title", required = true)
	protected String hdlTitle;
	@XmlElement(name = "txt_Teaser", required = true)
	protected String txtTeaser;
	@XmlElement(name = "stf_IsExternalSiteArticle", required = true)
	protected String stfIsExternalSiteArticle;
	@XmlElement(name = "stf_TrackingTitle", required = true)
	protected String stfTrackingTitle;
	@XmlElement(name = "stf_LinkLearnMore", required = true)
	protected String stfLinkLearnMore;
	@XmlElement(name = "stf_externalLink", required = true)
	protected String stfExternalLink;
	@XmlElement(name = "opt_isNewWindow", required = true)
	protected String optIsNewWindow;
	@XmlElement(name = "stf_TrackingEvent", required = true)
	protected String stfTrackingEvent;
	@XmlElement(name = "stf_ExternalLinkTitle", required = true)
	protected String stfExternalLinkTitle;
	@XmlElement(name = "med_File", required = true)
	protected String medFile;

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value) {
		this.url = value;
	}

	/**
	 * Gets the value of the hdlTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHdlTitle() {
		return hdlTitle;
	}

	/**
	 * Sets the value of the hdlTitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setHdlTitle(String value) {
		this.hdlTitle = value;
	}

	/**
	 * Gets the value of the txtTeaser property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTxtTeaser() {
		return txtTeaser;
	}

	/**
	 * Sets the value of the txtTeaser property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTxtTeaser(String value) {
		this.txtTeaser = value;
	}

	/**
	 * Gets the value of the stfIsExternalSiteArticle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfIsExternalSiteArticle() {
		return stfIsExternalSiteArticle;
	}

	/**
	 * Sets the value of the stfIsExternalSiteArticle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfIsExternalSiteArticle(String value) {
		this.stfIsExternalSiteArticle = value;
	}

	/**
	 * Gets the value of the stfTrackingTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfTrackingTitle() {
		return stfTrackingTitle;
	}

	/**
	 * Sets the value of the stfTrackingTitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfTrackingTitle(String value) {
		this.stfTrackingTitle = value;
	}

	/**
	 * Gets the value of the stfLinkLearnMore property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfLinkLearnMore() {
		return stfLinkLearnMore;
	}

	/**
	 * Sets the value of the stfLinkLearnMore property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfLinkLearnMore(String value) {
		this.stfLinkLearnMore = value;
	}

	/**
	 * Gets the value of the stfExternalLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfExternalLink() {
		return stfExternalLink;
	}

	/**
	 * Sets the value of the stfExternalLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfExternalLink(String value) {
		this.stfExternalLink = value;
	}

	/**
	 * Gets the value of the optIsNewWindow property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOptIsNewWindow() {
		return optIsNewWindow;
	}

	/**
	 * Sets the value of the optIsNewWindow property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOptIsNewWindow(String value) {
		this.optIsNewWindow = value;
	}

	/**
	 * Gets the value of the stfTrackingEvent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfTrackingEvent() {
		return stfTrackingEvent;
	}

	/**
	 * Sets the value of the stfTrackingEvent property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfTrackingEvent(String value) {
		this.stfTrackingEvent = value;
	}

	/**
	 * Gets the value of the stfExternalLinkTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfExternalLinkTitle() {
		return stfExternalLinkTitle;
	}

	/**
	 * Sets the value of the stfExternalLinkTitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfExternalLinkTitle(String value) {
		this.stfExternalLinkTitle = value;
	}

	/**
	 * Gets the value of the medFile property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMedFile() {
		return medFile;
	}

	/**
	 * Sets the value of the medFile property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMedFile(String value) {
		this.medFile = value;
	}

}
