//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BEDestinationsFeaturedLinksContainerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BEDestinationsFeaturedLinksContainerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txt_Header" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_FeaturedLinks" type="{}con_FeaturedLinksType"/>
 *         &lt;element name="anc_TitleLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEDestinationsFeaturedLinksContainerType", propOrder = { "txtHeader", "conFeaturedLinks",
	"ancTitleLink" })
public class BEDestinationsFeaturedLinksContainerType {

	@XmlElement(name = "txt_Header", required = true)
	protected String txtHeader;
	@XmlElement(name = "con_FeaturedLinks", required = true)
	protected ConFeaturedLinksType conFeaturedLinks;
	@XmlElement(name = "anc_TitleLink", required = true)
	protected String ancTitleLink;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the txtHeader property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTxtHeader() {
		return txtHeader;
	}

	/**
	 * Sets the value of the txtHeader property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTxtHeader(String value) {
		this.txtHeader = value;
	}

	/**
	 * Gets the value of the conFeaturedLinks property.
	 * 
	 * @return possible object is {@link ConFeaturedLinksType }
	 * 
	 */
	public ConFeaturedLinksType getConFeaturedLinks() {
		return conFeaturedLinks;
	}

	/**
	 * Sets the value of the conFeaturedLinks property.
	 * 
	 * @param value allowed object is {@link ConFeaturedLinksType }
	 * 
	 */
	public void setConFeaturedLinks(ConFeaturedLinksType value) {
		this.conFeaturedLinks = value;
	}

	/**
	 * Gets the value of the ancTitleLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncTitleLink() {
		return ancTitleLink;
	}

	/**
	 * Sets the value of the ancTitleLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncTitleLink(String value) {
		this.ancTitleLink = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
