//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BEGenericListWithHeaderItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BEGenericListWithHeaderItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anc_article" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="med_article" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEGenericListWithHeaderItemType", propOrder = {
    "ancArticle",
    "medArticle",
    "stfTitle"
})
public class BEGenericListWithHeaderItemType {

    @XmlElement(name = "anc_article", required = true)
    protected String ancArticle;
    @XmlElement(name = "med_article", required = true)
    protected String medArticle;
    @XmlElement(name = "stf_title", required = true)
    protected String stfTitle;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the ancArticle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAncArticle() {
        return ancArticle;
    }

    /**
     * Sets the value of the ancArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAncArticle(String value) {
        this.ancArticle = value;
    }

    /**
     * Gets the value of the medArticle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedArticle() {
        return medArticle;
    }

    /**
     * Sets the value of the medArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedArticle(String value) {
        this.medArticle = value;
    }

    /**
     * Gets the value of the stfTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfTitle() {
        return stfTitle;
    }

    /**
     * Sets the value of the stfTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfTitle(String value) {
        this.stfTitle = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
