//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BEGenericListWithHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BEGenericListWithHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txt_content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_items" type="{}con_itemsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEGenericListWithHeaderType", propOrder = {
    "txtContent",
    "conItems"
})
public class BEGenericListWithHeaderType {

    @XmlElement(name = "txt_content", required = true)
    protected String txtContent;
    @XmlElement(name = "con_items", required = true)
    protected ConItemsType conItems;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the txtContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxtContent() {
        return txtContent;
    }

    /**
     * Sets the value of the txtContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxtContent(String value) {
        this.txtContent = value;
    }

    /**
     * Gets the value of the conItems property.
     * 
     * @return
     *     possible object is
     *     {@link ConItemsType }
     *     
     */
    public ConItemsType getConItems() {
        return conItems;
    }

    /**
     * Sets the value of the conItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConItemsType }
     *     
     */
    public void setConItems(ConItemsType value) {
        this.conItems = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
