//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BEHomeCarouselType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BEHomeCarouselType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="img_CarouselItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_CarouselItemLinkText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_ScrollerLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_CarouselItemLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEHomeCarouselType", propOrder = { "imgCarouselItem", "stfCarouselItemLinkText", "stfScrollerLabel",
	"ancCarouselItemLink" })
public class BEHomeCarouselType {

	@XmlElement(name = "img_CarouselItem", required = true)
	protected String imgCarouselItem;
	@XmlElement(name = "stf_CarouselItemLinkText", required = true)
	protected String stfCarouselItemLinkText;
	@XmlElement(name = "stf_ScrollerLabel", required = true)
	protected String stfScrollerLabel;
	@XmlElement(name = "anc_CarouselItemLink", required = true)
	protected String ancCarouselItemLink;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the imgCarouselItem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImgCarouselItem() {
		return imgCarouselItem;
	}

	/**
	 * Sets the value of the imgCarouselItem property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setImgCarouselItem(String value) {
		this.imgCarouselItem = value;
	}

	/**
	 * Gets the value of the stfCarouselItemLinkText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfCarouselItemLinkText() {
		return stfCarouselItemLinkText;
	}

	/**
	 * Sets the value of the stfCarouselItemLinkText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfCarouselItemLinkText(String value) {
		this.stfCarouselItemLinkText = value;
	}

	/**
	 * Gets the value of the stfScrollerLabel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfScrollerLabel() {
		return stfScrollerLabel;
	}

	/**
	 * Sets the value of the stfScrollerLabel property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfScrollerLabel(String value) {
		this.stfScrollerLabel = value;
	}

	/**
	 * Gets the value of the ancCarouselItemLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncCarouselItemLink() {
		return ancCarouselItemLink;
	}

	/**
	 * Sets the value of the ancCarouselItemLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncCarouselItemLink(String value) {
		this.ancCarouselItemLink = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
