//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BEHomeNewsSectionContainerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BEHomeNewsSectionContainerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_related_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txt_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_items" type="{}con_itemsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEHomeNewsSectionContainerType", propOrder = {
    "hdlTitle",
    "imgImage",
    "stfDate",
    "stfHeading",
    "stfRelatedLabel",
    "txtDescription",
    "conItems"
})
public class BEHomeNewsSectionContainerType {

    @XmlElement(name = "hdl_Title", required = true)
    protected String hdlTitle;
    @XmlElement(name = "img_image", required = true)
    protected String imgImage;
    @XmlElement(name = "stf_date", required = true)
    protected String stfDate;
    @XmlElement(name = "stf_heading", required = true)
    protected String stfHeading;
    @XmlElement(name = "stf_related_label", required = true)
    protected String stfRelatedLabel;
    @XmlElement(name = "txt_description", required = true)
    protected String txtDescription;
    @XmlElement(name = "con_items", required = true)
    protected ConItemsType conItems;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the hdlTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdlTitle() {
        return hdlTitle;
    }

    /**
     * Sets the value of the hdlTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdlTitle(String value) {
        this.hdlTitle = value;
    }

    /**
     * Gets the value of the imgImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgImage() {
        return imgImage;
    }

    /**
     * Sets the value of the imgImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgImage(String value) {
        this.imgImage = value;
    }

    /**
     * Gets the value of the stfDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfDate() {
        return stfDate;
    }

    /**
     * Sets the value of the stfDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfDate(String value) {
        this.stfDate = value;
    }

    /**
     * Gets the value of the stfHeading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfHeading() {
        return stfHeading;
    }

    /**
     * Sets the value of the stfHeading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfHeading(String value) {
        this.stfHeading = value;
    }

    /**
     * Gets the value of the stfRelatedLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfRelatedLabel() {
        return stfRelatedLabel;
    }

    /**
     * Sets the value of the stfRelatedLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfRelatedLabel(String value) {
        this.stfRelatedLabel = value;
    }

    /**
     * Gets the value of the txtDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxtDescription() {
        return txtDescription;
    }

    /**
     * Sets the value of the txtDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxtDescription(String value) {
        this.txtDescription = value;
    }

    /**
     * Gets the value of the conItems property.
     * 
     * @return
     *     possible object is
     *     {@link ConItemsType }
     *     
     */
    public ConItemsType getConItems() {
        return conItems;
    }

    /**
     * Sets the value of the conItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConItemsType }
     *     
     */
    public void setConItems(ConItemsType value) {
        this.conItems = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
