//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for con_bottomContainerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="con_bottomContainerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BEHomeNewsSectionContainer" type="{}BEHomeNewsSectionContainerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "con_bottomContainerType", propOrder = { "beHomeNewsSectionContainer" })
public class ConBottomContainerType {

	@XmlElement(name = "BEHomeNewsSectionContainer", required = true)
	protected BEHomeNewsSectionContainerType beHomeNewsSectionContainer;

	/**
	 * Gets the value of the beHomeNewsSectionContainer property.
	 * 
	 * @return possible object is {@link BEHomeNewsSectionContainerType }
	 * 
	 */
	public BEHomeNewsSectionContainerType getBEHomeNewsSectionContainer() {
		return beHomeNewsSectionContainer;
	}

	/**
	 * Sets the value of the beHomeNewsSectionContainer property.
	 * 
	 * @param value allowed object is {@link BEHomeNewsSectionContainerType }
	 * 
	 */
	public void setBEHomeNewsSectionContainer(BEHomeNewsSectionContainerType value) {
		this.beHomeNewsSectionContainer = value;
	}

}
