//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for con_CookiePolicyMessageType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="con_CookiePolicyMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EUCookieConsentHeader" type="{}EUCookieConsentHeaderType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "con_CookiePolicyMessageType", propOrder = { "euCookieConsentHeader" })
public class ConCookiePolicyMessageType {

	@XmlElement(name = "EUCookieConsentHeader", required = true)
	protected EUCookieConsentHeaderType euCookieConsentHeader;

	/**
	 * Gets the value of the euCookieConsentHeader property.
	 * 
	 * @return possible object is {@link EUCookieConsentHeaderType }
	 * 
	 */
	public EUCookieConsentHeaderType getEUCookieConsentHeader() {
		return euCookieConsentHeader;
	}

	/**
	 * Sets the value of the euCookieConsentHeader property.
	 * 
	 * @param value allowed object is {@link EUCookieConsentHeaderType }
	 * 
	 */
	public void setEUCookieConsentHeader(EUCookieConsentHeaderType value) {
		this.euCookieConsentHeader = value;
	}

}
