//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for con_SpecialOffersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="con_SpecialOffersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpecialOffersBox" type="{}SpecialOffersBoxType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "con_SpecialOffersType", propOrder = {
    "specialOffersBox"
})
public class ConSpecialOffersType {

    @XmlElement(name = "SpecialOffersBox", required = true)
    protected SpecialOffersBoxType specialOffersBox;

    /**
     * Gets the value of the specialOffersBox property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialOffersBoxType }
     *     
     */
    public SpecialOffersBoxType getSpecialOffersBox() {
        return specialOffersBox;
    }

    /**
     * Sets the value of the specialOffersBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialOffersBoxType }
     *     
     */
    public void setSpecialOffersBox(SpecialOffersBoxType value) {
        this.specialOffersBox = value;
    }

}
