//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for con_sidebarType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="con_sidebarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BENavPanelSnapshot" type="{}BENavPanelSnapshotType" minOccurs="0"/>
 *         &lt;element name="BENavPanelPageLinks" type="{}BENavPanelPageLinksType" minOccurs="0"/>
 *         &lt;element name="BEGeneralContentSidebarLinks" type="{}BEGeneralContentSidebarLinksType" minOccurs="0"/>
 *         &lt;element name="BENavPanelNewsletterSignup" type="{}BENavPanelNewsletterSignupType" minOccurs="0"/>
 *         &lt;element name="BEAccommodationSearchFilter" type="{}BEAccommodationSearchFilterType" minOccurs="0"/>
 *         &lt;element name="BEGallerySidebarDynamicLinks" type="{}BEGallerySidebarDynamicLinksType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BEWhatsOnSearchFilter" type="{}BEWhatsOnSearchFilterType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "con_sidebarType", propOrder = { "content" })
public class ConSidebarType {

	@XmlElementRefs({ @XmlElementRef(name = "BEAccommodationSearchFilter", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BEGeneralContentSidebarLinks", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BENavPanelNewsletterSignup", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BENavPanelSnapshot", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BEGallerySidebarDynamicLinks", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BENavPanelPageLinks", type = JAXBElement.class, required = false),
		@XmlElementRef(name = "BEWhatsOnSearchFilter", type = JAXBElement.class, required = false) })
	@XmlMixed
	protected List<Serializable> content;

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link BEAccommodationSearchFilterType }
	 * {@code >} {@link String } {@link JAXBElement }{@code <}
	 * {@link BEGeneralContentSidebarLinksType }{@code >} {@link JAXBElement }
	 * {@code <}{@link BENavPanelNewsletterSignupType }{@code >}
	 * {@link JAXBElement }{@code <}{@link BENavPanelSnapshotType }{@code >}
	 * {@link JAXBElement }{@code <}{@link BEGallerySidebarDynamicLinksType }
	 * {@code >} {@link JAXBElement }{@code <}{@link BENavPanelPageLinksType }
	 * {@code >} {@link JAXBElement }{@code <}{@link BEWhatsOnSearchFilterType }
	 * {@code >}
	 * 
	 * 
	 */
	public List<Serializable> getContent() {
		if (content == null) {
			content = new ArrayList<Serializable>();
		}
		return this.content;
	}

}
