//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsumerHomepageFoundationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsumerHomepageFoundationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TA_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inf_PageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_SearchThumbnail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_Background" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_ImageLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_CookiePolicyMessage" type="{}con_CookiePolicyMessageType"/>
 *         &lt;element name="con_GlobalHeader" type="{}con_GlobalHeaderType"/>
 *         &lt;element name="con_HomepageIntro" type="{}con_HomepageIntroType"/>
 *         &lt;element name="con_Map" type="{}con_MapType"/>
 *         &lt;element name="con_News" type="{}con_NewsType"/>
 *         &lt;element name="con_SpecialOffers" type="{}con_SpecialOffersType"/>
 *         &lt;element name="con_FeatureBox" type="{}con_FeatureBoxType"/>
 *         &lt;element name="con_Carousel" type="{}con_CarouselType"/>
 *         &lt;element name="con_Video" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_Footer" type="{}con_FooterType"/>
 *         &lt;element name="con_Banner" type="{}con_BannerType"/>
 *         &lt;element name="con_FooterScript" type="{}con_FooterScriptType"/>
 *         &lt;element name="lst_Promotions" type="{}lst_PromotionsType"/>
 *         &lt;element name="lst_Subpages" type="{}lst_SubpagesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pageID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsumerHomepageFoundationType", propOrder = {
    "taTitle",
    "hdlTitle",
    "infPageId",
    "stfDescription",
    "stfKeywords",
    "imgSearchThumbnail",
    "imgBackground",
    "stfImageLocation",
    "conCookiePolicyMessage",
    "conGlobalHeader",
    "conHomepageIntro",
    "conMap",
    "conNews",
    "conSpecialOffers",
    "conFeatureBox",
    "conCarousel",
    "conVideo",
    "conFooter",
    "conBanner",
    "conFooterScript",
    "lstPromotions",
    "lstSubpages"
})
public class ConsumerHomepageFoundationType {

    @XmlElement(name = "TA_Title", required = true)
    protected String taTitle;
    @XmlElement(name = "hdl_Title", required = true)
    protected String hdlTitle;
    @XmlElement(name = "inf_PageId", required = true)
    protected String infPageId;
    @XmlElement(name = "stf_description", required = true)
    protected String stfDescription;
    @XmlElement(name = "stf_keywords", required = true)
    protected String stfKeywords;
    @XmlElement(name = "img_SearchThumbnail", required = true)
    protected String imgSearchThumbnail;
    @XmlElement(name = "img_Background", required = true)
    protected String imgBackground;
    @XmlElement(name = "stf_ImageLocation", required = true)
    protected String stfImageLocation;
    @XmlElement(name = "con_CookiePolicyMessage", required = true)
    protected ConCookiePolicyMessageType conCookiePolicyMessage;
    @XmlElement(name = "con_GlobalHeader", required = true)
    protected ConGlobalHeaderType conGlobalHeader;
    @XmlElement(name = "con_HomepageIntro", required = true)
    protected ConHomepageIntroType conHomepageIntro;
    @XmlElement(name = "con_Map", required = true)
    protected ConMapType conMap;
    @XmlElement(name = "con_News", required = true)
    protected ConNewsType conNews;
    @XmlElement(name = "con_SpecialOffers", required = true)
    protected ConSpecialOffersType conSpecialOffers;
    @XmlElement(name = "con_FeatureBox", required = true)
    protected ConFeatureBoxType conFeatureBox;
    @XmlElement(name = "con_Carousel", required = true)
    protected ConCarouselType conCarousel;
    @XmlElement(name = "con_Video", required = true)
    protected String conVideo;
    @XmlElement(name = "con_Footer", required = true)
    protected ConFooterType conFooter;
    @XmlElement(name = "con_Banner", required = true)
    protected ConBannerType conBanner;
    @XmlElement(name = "con_FooterScript", required = true)
    protected ConFooterScriptType conFooterScript;
    @XmlElement(name = "lst_Promotions", required = true)
    protected LstPromotionsType lstPromotions;
    @XmlElement(name = "lst_Subpages", required = true)
    protected LstSubpagesType lstSubpages;
    @XmlAttribute(name = "pageID")
    protected String pageID;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the taTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTATitle() {
        return taTitle;
    }

    /**
     * Sets the value of the taTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTATitle(String value) {
        this.taTitle = value;
    }

    /**
     * Gets the value of the hdlTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdlTitle() {
        return hdlTitle;
    }

    /**
     * Sets the value of the hdlTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdlTitle(String value) {
        this.hdlTitle = value;
    }

    /**
     * Gets the value of the infPageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfPageId() {
        return infPageId;
    }

    /**
     * Sets the value of the infPageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfPageId(String value) {
        this.infPageId = value;
    }

    /**
     * Gets the value of the stfDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfDescription() {
        return stfDescription;
    }

    /**
     * Sets the value of the stfDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfDescription(String value) {
        this.stfDescription = value;
    }

    /**
     * Gets the value of the stfKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfKeywords() {
        return stfKeywords;
    }

    /**
     * Sets the value of the stfKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfKeywords(String value) {
        this.stfKeywords = value;
    }

    /**
     * Gets the value of the imgSearchThumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgSearchThumbnail() {
        return imgSearchThumbnail;
    }

    /**
     * Sets the value of the imgSearchThumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgSearchThumbnail(String value) {
        this.imgSearchThumbnail = value;
    }

    /**
     * Gets the value of the imgBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgBackground() {
        return imgBackground;
    }

    /**
     * Sets the value of the imgBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgBackground(String value) {
        this.imgBackground = value;
    }

    /**
     * Gets the value of the stfImageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfImageLocation() {
        return stfImageLocation;
    }

    /**
     * Sets the value of the stfImageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfImageLocation(String value) {
        this.stfImageLocation = value;
    }

    /**
     * Gets the value of the conCookiePolicyMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ConCookiePolicyMessageType }
     *     
     */
    public ConCookiePolicyMessageType getConCookiePolicyMessage() {
        return conCookiePolicyMessage;
    }

    /**
     * Sets the value of the conCookiePolicyMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConCookiePolicyMessageType }
     *     
     */
    public void setConCookiePolicyMessage(ConCookiePolicyMessageType value) {
        this.conCookiePolicyMessage = value;
    }

    /**
     * Gets the value of the conGlobalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ConGlobalHeaderType }
     *     
     */
    public ConGlobalHeaderType getConGlobalHeader() {
        return conGlobalHeader;
    }

    /**
     * Sets the value of the conGlobalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConGlobalHeaderType }
     *     
     */
    public void setConGlobalHeader(ConGlobalHeaderType value) {
        this.conGlobalHeader = value;
    }

    /**
     * Gets the value of the conHomepageIntro property.
     * 
     * @return
     *     possible object is
     *     {@link ConHomepageIntroType }
     *     
     */
    public ConHomepageIntroType getConHomepageIntro() {
        return conHomepageIntro;
    }

    /**
     * Sets the value of the conHomepageIntro property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConHomepageIntroType }
     *     
     */
    public void setConHomepageIntro(ConHomepageIntroType value) {
        this.conHomepageIntro = value;
    }

    /**
     * Gets the value of the conMap property.
     * 
     * @return
     *     possible object is
     *     {@link ConMapType }
     *     
     */
    public ConMapType getConMap() {
        return conMap;
    }

    /**
     * Sets the value of the conMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConMapType }
     *     
     */
    public void setConMap(ConMapType value) {
        this.conMap = value;
    }

    /**
     * Gets the value of the conNews property.
     * 
     * @return
     *     possible object is
     *     {@link ConNewsType }
     *     
     */
    public ConNewsType getConNews() {
        return conNews;
    }

    /**
     * Sets the value of the conNews property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConNewsType }
     *     
     */
    public void setConNews(ConNewsType value) {
        this.conNews = value;
    }

    /**
     * Gets the value of the conSpecialOffers property.
     * 
     * @return
     *     possible object is
     *     {@link ConSpecialOffersType }
     *     
     */
    public ConSpecialOffersType getConSpecialOffers() {
        return conSpecialOffers;
    }

    /**
     * Sets the value of the conSpecialOffers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConSpecialOffersType }
     *     
     */
    public void setConSpecialOffers(ConSpecialOffersType value) {
        this.conSpecialOffers = value;
    }

    /**
     * Gets the value of the conFeatureBox property.
     * 
     * @return
     *     possible object is
     *     {@link ConFeatureBoxType }
     *     
     */
    public ConFeatureBoxType getConFeatureBox() {
        return conFeatureBox;
    }

    /**
     * Sets the value of the conFeatureBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFeatureBoxType }
     *     
     */
    public void setConFeatureBox(ConFeatureBoxType value) {
        this.conFeatureBox = value;
    }

    /**
     * Gets the value of the conCarousel property.
     * 
     * @return
     *     possible object is
     *     {@link ConCarouselType }
     *     
     */
    public ConCarouselType getConCarousel() {
        return conCarousel;
    }

    /**
     * Sets the value of the conCarousel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConCarouselType }
     *     
     */
    public void setConCarousel(ConCarouselType value) {
        this.conCarousel = value;
    }

    /**
     * Gets the value of the conVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConVideo() {
        return conVideo;
    }

    /**
     * Sets the value of the conVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConVideo(String value) {
        this.conVideo = value;
    }

    /**
     * Gets the value of the conFooter property.
     * 
     * @return
     *     possible object is
     *     {@link ConFooterType }
     *     
     */
    public ConFooterType getConFooter() {
        return conFooter;
    }

    /**
     * Sets the value of the conFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFooterType }
     *     
     */
    public void setConFooter(ConFooterType value) {
        this.conFooter = value;
    }

    /**
     * Gets the value of the conBanner property.
     * 
     * @return
     *     possible object is
     *     {@link ConBannerType }
     *     
     */
    public ConBannerType getConBanner() {
        return conBanner;
    }

    /**
     * Sets the value of the conBanner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConBannerType }
     *     
     */
    public void setConBanner(ConBannerType value) {
        this.conBanner = value;
    }

    /**
     * Gets the value of the conFooterScript property.
     * 
     * @return
     *     possible object is
     *     {@link ConFooterScriptType }
     *     
     */
    public ConFooterScriptType getConFooterScript() {
        return conFooterScript;
    }

    /**
     * Sets the value of the conFooterScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFooterScriptType }
     *     
     */
    public void setConFooterScript(ConFooterScriptType value) {
        this.conFooterScript = value;
    }

    /**
     * Gets the value of the lstPromotions property.
     * 
     * @return
     *     possible object is
     *     {@link LstPromotionsType }
     *     
     */
    public LstPromotionsType getLstPromotions() {
        return lstPromotions;
    }

    /**
     * Sets the value of the lstPromotions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LstPromotionsType }
     *     
     */
    public void setLstPromotions(LstPromotionsType value) {
        this.lstPromotions = value;
    }

    /**
     * Gets the value of the lstSubpages property.
     * 
     * @return
     *     possible object is
     *     {@link LstSubpagesType }
     *     
     */
    public LstSubpagesType getLstSubpages() {
        return lstSubpages;
    }

    /**
     * Sets the value of the lstSubpages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LstSubpagesType }
     *     
     */
    public void setLstSubpages(LstSubpagesType value) {
        this.lstSubpages = value;
    }

    /**
     * Gets the value of the pageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageID() {
        return pageID;
    }

    /**
     * Sets the value of the pageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageID(String value) {
        this.pageID = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
