//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for con_storiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="con_storiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BEHomeFeaturedOverlayText" type="{}BEHomeFeaturedOverlayTextType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "con_storiesType", propOrder = {
    "beHomeFeaturedOverlayText"
})
public class ConStoriesType {

    @XmlElement(name = "BEHomeFeaturedOverlayText")
    protected List<BEHomeFeaturedOverlayTextType> beHomeFeaturedOverlayText;

    /**
     * Gets the value of the beHomeFeaturedOverlayText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beHomeFeaturedOverlayText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBEHomeFeaturedOverlayText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BEHomeFeaturedOverlayTextType }
     * 
     * 
     */
    public List<BEHomeFeaturedOverlayTextType> getBEHomeFeaturedOverlayText() {
        if (beHomeFeaturedOverlayText == null) {
            beHomeFeaturedOverlayText = new ArrayList<BEHomeFeaturedOverlayTextType>();
        }
        return this.beHomeFeaturedOverlayText;
    }

}
