//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EUCookieConsentHeaderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EUCookieConsentHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stf_CookieMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_CookiePolicyTargetedCountries" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_LinkText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_PolicyLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EUCookieConsentHeaderType", propOrder = { "stfCookieMessage", "stfCookiePolicyTargetedCountries",
	"stfLinkText", "ancPolicyLink" })
public class EUCookieConsentHeaderType {

	@XmlElement(name = "stf_CookieMessage", required = true)
	protected String stfCookieMessage;
	@XmlElement(name = "stf_CookiePolicyTargetedCountries", required = true)
	protected String stfCookiePolicyTargetedCountries;
	@XmlElement(name = "stf_LinkText", required = true)
	protected String stfLinkText;
	@XmlElement(name = "anc_PolicyLink", required = true)
	protected String ancPolicyLink;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the stfCookieMessage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfCookieMessage() {
		return stfCookieMessage;
	}

	/**
	 * Sets the value of the stfCookieMessage property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfCookieMessage(String value) {
		this.stfCookieMessage = value;
	}

	/**
	 * Gets the value of the stfCookiePolicyTargetedCountries property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfCookiePolicyTargetedCountries() {
		return stfCookiePolicyTargetedCountries;
	}

	/**
	 * Sets the value of the stfCookiePolicyTargetedCountries property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfCookiePolicyTargetedCountries(String value) {
		this.stfCookiePolicyTargetedCountries = value;
	}

	/**
	 * Gets the value of the stfLinkText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfLinkText() {
		return stfLinkText;
	}

	/**
	 * Sets the value of the stfLinkText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfLinkText(String value) {
		this.stfLinkText = value;
	}

	/**
	 * Gets the value of the ancPolicyLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncPolicyLink() {
		return ancPolicyLink;
	}

	/**
	 * Sets the value of the ancPolicyLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncPolicyLink(String value) {
		this.ancPolicyLink = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
