//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExploreMapHalfLandingPageFoundationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExploreMapHalfLandingPageFoundationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TA_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_SearchThumbnail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_background" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_PageHeading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_NavigationTagLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txt_SpotlightTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_GlobalHeader" type="{}con_GlobalHeaderType"/>
 *         &lt;element name="con_css_js" type="{}con_css_jsType"/>
 *         &lt;element name="con_LanguageSitemap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_Body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_RHSModules" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_Video" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_page_layout" type="{}con_page_layoutType"/>
 *         &lt;element name="con_Footer" type="{}con_FooterType"/>
 *         &lt;element name="con_FooterScript" type="{}con_FooterScriptType"/>
 *         &lt;element name="lst_Subpages" type="{}lst_SubpagesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pageID" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExploreMapHalfLandingPageFoundationType", propOrder = {
    "taTitle",
    "hdlTitle",
    "stfDescription",
    "stfKeywords",
    "imgSearchThumbnail",
    "imgBackground",
    "stfPageHeading",
    "stfNavigationTagLine",
    "txtSpotlightTag",
    "conGlobalHeader",
    "conCssJs",
    "conLanguageSitemap",
    "conBody",
    "conRHSModules",
    "conVideo",
    "conPageLayout",
    "conFooter",
    "conFooterScript",
    "lstSubpages"
})
public class ExploreMapHalfLandingPageFoundationType {

    @XmlElement(name = "TA_Title", required = true)
    protected String taTitle;
    @XmlElement(name = "hdl_Title", required = true)
    protected String hdlTitle;
    @XmlElement(name = "stf_description", required = true)
    protected String stfDescription;
    @XmlElement(name = "stf_keywords", required = true)
    protected String stfKeywords;
    @XmlElement(name = "img_SearchThumbnail", required = true)
    protected String imgSearchThumbnail;
    @XmlElement(name = "img_background", required = true)
    protected String imgBackground;
    @XmlElement(name = "stf_PageHeading", required = true)
    protected String stfPageHeading;
    @XmlElement(name = "stf_NavigationTagLine", required = true)
    protected String stfNavigationTagLine;
    @XmlElement(name = "txt_SpotlightTag", required = true)
    protected String txtSpotlightTag;
    @XmlElement(name = "con_GlobalHeader", required = true)
    protected ConGlobalHeaderType conGlobalHeader;
    @XmlElement(name = "con_css_js", required = true)
    protected ConCssJsType conCssJs;
    @XmlElement(name = "con_LanguageSitemap", required = true)
    protected String conLanguageSitemap;
    @XmlElement(name = "con_Body", required = true)
    protected String conBody;
    @XmlElement(name = "con_RHSModules", required = true)
    protected String conRHSModules;
    @XmlElement(name = "con_Video", required = true)
    protected String conVideo;
    @XmlElement(name = "con_page_layout", required = true)
    protected ConPageLayoutType conPageLayout;
    @XmlElement(name = "con_Footer", required = true)
    protected ConFooterType conFooter;
    @XmlElement(name = "con_FooterScript", required = true)
    protected ConFooterScriptType conFooterScript;
    @XmlElement(name = "lst_Subpages", required = true)
    protected LstSubpagesType lstSubpages;
    @XmlAttribute(name = "pageID")
    protected Short pageID;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the taTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTATitle() {
        return taTitle;
    }

    /**
     * Sets the value of the taTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTATitle(String value) {
        this.taTitle = value;
    }

    /**
     * Gets the value of the hdlTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdlTitle() {
        return hdlTitle;
    }

    /**
     * Sets the value of the hdlTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdlTitle(String value) {
        this.hdlTitle = value;
    }

    /**
     * Gets the value of the stfDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfDescription() {
        return stfDescription;
    }

    /**
     * Sets the value of the stfDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfDescription(String value) {
        this.stfDescription = value;
    }

    /**
     * Gets the value of the stfKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfKeywords() {
        return stfKeywords;
    }

    /**
     * Sets the value of the stfKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfKeywords(String value) {
        this.stfKeywords = value;
    }

    /**
     * Gets the value of the imgSearchThumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgSearchThumbnail() {
        return imgSearchThumbnail;
    }

    /**
     * Sets the value of the imgSearchThumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgSearchThumbnail(String value) {
        this.imgSearchThumbnail = value;
    }

    /**
     * Gets the value of the imgBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgBackground() {
        return imgBackground;
    }

    /**
     * Sets the value of the imgBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgBackground(String value) {
        this.imgBackground = value;
    }

    /**
     * Gets the value of the stfPageHeading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfPageHeading() {
        return stfPageHeading;
    }

    /**
     * Sets the value of the stfPageHeading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfPageHeading(String value) {
        this.stfPageHeading = value;
    }

    /**
     * Gets the value of the stfNavigationTagLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfNavigationTagLine() {
        return stfNavigationTagLine;
    }

    /**
     * Sets the value of the stfNavigationTagLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfNavigationTagLine(String value) {
        this.stfNavigationTagLine = value;
    }

    /**
     * Gets the value of the txtSpotlightTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxtSpotlightTag() {
        return txtSpotlightTag;
    }

    /**
     * Sets the value of the txtSpotlightTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxtSpotlightTag(String value) {
        this.txtSpotlightTag = value;
    }

    /**
     * Gets the value of the conGlobalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ConGlobalHeaderType }
     *     
     */
    public ConGlobalHeaderType getConGlobalHeader() {
        return conGlobalHeader;
    }

    /**
     * Sets the value of the conGlobalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConGlobalHeaderType }
     *     
     */
    public void setConGlobalHeader(ConGlobalHeaderType value) {
        this.conGlobalHeader = value;
    }

    /**
     * Gets the value of the conCssJs property.
     * 
     * @return
     *     possible object is
     *     {@link ConCssJsType }
     *     
     */
    public ConCssJsType getConCssJs() {
        return conCssJs;
    }

    /**
     * Sets the value of the conCssJs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConCssJsType }
     *     
     */
    public void setConCssJs(ConCssJsType value) {
        this.conCssJs = value;
    }

    /**
     * Gets the value of the conLanguageSitemap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConLanguageSitemap() {
        return conLanguageSitemap;
    }

    /**
     * Sets the value of the conLanguageSitemap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConLanguageSitemap(String value) {
        this.conLanguageSitemap = value;
    }

    /**
     * Gets the value of the conBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConBody() {
        return conBody;
    }

    /**
     * Sets the value of the conBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConBody(String value) {
        this.conBody = value;
    }

    /**
     * Gets the value of the conRHSModules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConRHSModules() {
        return conRHSModules;
    }

    /**
     * Sets the value of the conRHSModules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConRHSModules(String value) {
        this.conRHSModules = value;
    }

    /**
     * Gets the value of the conVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConVideo() {
        return conVideo;
    }

    /**
     * Sets the value of the conVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConVideo(String value) {
        this.conVideo = value;
    }

    /**
     * Gets the value of the conPageLayout property.
     * 
     * @return
     *     possible object is
     *     {@link ConPageLayoutType }
     *     
     */
    public ConPageLayoutType getConPageLayout() {
        return conPageLayout;
    }

    /**
     * Sets the value of the conPageLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConPageLayoutType }
     *     
     */
    public void setConPageLayout(ConPageLayoutType value) {
        this.conPageLayout = value;
    }

    /**
     * Gets the value of the conFooter property.
     * 
     * @return
     *     possible object is
     *     {@link ConFooterType }
     *     
     */
    public ConFooterType getConFooter() {
        return conFooter;
    }

    /**
     * Sets the value of the conFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFooterType }
     *     
     */
    public void setConFooter(ConFooterType value) {
        this.conFooter = value;
    }

    /**
     * Gets the value of the conFooterScript property.
     * 
     * @return
     *     possible object is
     *     {@link ConFooterScriptType }
     *     
     */
    public ConFooterScriptType getConFooterScript() {
        return conFooterScript;
    }

    /**
     * Sets the value of the conFooterScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFooterScriptType }
     *     
     */
    public void setConFooterScript(ConFooterScriptType value) {
        this.conFooterScript = value;
    }

    /**
     * Gets the value of the lstSubpages property.
     * 
     * @return
     *     possible object is
     *     {@link LstSubpagesType }
     *     
     */
    public LstSubpagesType getLstSubpages() {
        return lstSubpages;
    }

    /**
     * Sets the value of the lstSubpages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LstSubpagesType }
     *     
     */
    public void setLstSubpages(LstSubpagesType value) {
        this.lstSubpages = value;
    }

    /**
     * Gets the value of the pageID property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPageID() {
        return pageID;
    }

    /**
     * Sets the value of the pageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPageID(Short value) {
        this.pageID = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
