//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FullWidthCampaignLayoutType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="FullWidthCampaignLayoutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conMainContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_Body" type="{}con_BodyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FullWidthCampaignLayoutType", propOrder = { "conMainContent", "conBody" })
public class FullWidthCampaignLayoutType {

	@XmlElement(required = true)
	protected String conMainContent;
	@XmlElement(name = "con_Body", required = true)
	protected ConBodyType conBody;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the conMainContent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConMainContent() {
		return conMainContent;
	}

	/**
	 * Sets the value of the conMainContent property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setConMainContent(String value) {
		this.conMainContent = value;
	}

	/**
	 * Gets the value of the conBody property.
	 * 
	 * @return possible object is {@link ConBodyType }
	 * 
	 */
	public ConBodyType getConBody() {
		return conBody;
	}

	/**
	 * Sets the value of the conBody property.
	 * 
	 * @param value allowed object is {@link ConBodyType }
	 * 
	 */
	public void setConBody(ConBodyType value) {
		this.conBody = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
