//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for HomepageNewsHolderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="HomepageNewsHolderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anc_ManagementPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_VideoManagementPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="con_NewsItems" type="{}con_NewsItemsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HomepageNewsHolderType", propOrder = { "ancManagementPage", "ancVideoManagementPage", "conNewsItems" })
public class HomepageNewsHolderType {

	@XmlElement(name = "anc_ManagementPage", required = true)
	protected String ancManagementPage;
	@XmlElement(name = "anc_VideoManagementPage", required = true)
	protected String ancVideoManagementPage;
	@XmlElement(name = "con_NewsItems", required = true)
	protected ConNewsItemsType conNewsItems;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the ancManagementPage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncManagementPage() {
		return ancManagementPage;
	}

	/**
	 * Sets the value of the ancManagementPage property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncManagementPage(String value) {
		this.ancManagementPage = value;
	}

	/**
	 * Gets the value of the ancVideoManagementPage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncVideoManagementPage() {
		return ancVideoManagementPage;
	}

	/**
	 * Sets the value of the ancVideoManagementPage property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncVideoManagementPage(String value) {
		this.ancVideoManagementPage = value;
	}

	/**
	 * Gets the value of the conNewsItems property.
	 * 
	 * @return possible object is {@link ConNewsItemsType }
	 * 
	 */
	public ConNewsItemsType getConNewsItems() {
		return conNewsItems;
	}

	/**
	 * Sets the value of the conNewsItems property.
	 * 
	 * @param value allowed object is {@link ConNewsItemsType }
	 * 
	 */
	public void setConNewsItems(ConNewsItemsType value) {
		this.conNewsItems = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
