//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lst_LinkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lst_LinkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_Event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_Link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lst_LinkType", propOrder = { "url", "imgEvent", "ancLink" })
public class LstLinkType {

	@XmlElement(required = true)
	protected String url;
	@XmlElement(name = "img_Event", required = true)
	protected String imgEvent;
	@XmlElement(name = "anc_Link", required = true)
	protected String ancLink;

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value) {
		this.url = value;
	}

	/**
	 * Gets the value of the imgEvent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImgEvent() {
		return imgEvent;
	}

	/**
	 * Sets the value of the imgEvent property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setImgEvent(String value) {
		this.imgEvent = value;
	}

	/**
	 * Gets the value of the ancLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncLink() {
		return ancLink;
	}

	/**
	 * Sets the value of the ancLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncLink(String value) {
		this.ancLink = value;
	}

}
