//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//


package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialOffersItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialOffersItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hdl_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opt_Random" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_Thumbnail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_ThumnailTeaserOnPageCaption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img_ThumbnailTeaserOnPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anc_ListItems" type="{}anc_ListItemsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialOffersItemType", propOrder = {
    "hdlTitle",
    "optRandom",
    "imgThumbnail",
    "stfThumnailTeaserOnPageCaption",
    "imgThumbnailTeaserOnPage",
    "ancListItems"
})
public class SpecialOffersItemType {

    @XmlElement(name = "hdl_Title", required = true)
    protected String hdlTitle;
    @XmlElement(name = "opt_Random", required = true)
    protected String optRandom;
    @XmlElement(name = "img_Thumbnail", required = true)
    protected String imgThumbnail;
    @XmlElement(name = "stf_ThumnailTeaserOnPageCaption", required = true)
    protected String stfThumnailTeaserOnPageCaption;
    @XmlElement(name = "img_ThumbnailTeaserOnPage", required = true)
    protected String imgThumbnailTeaserOnPage;
    @XmlElement(name = "anc_ListItems", required = true)
    protected AncListItemsType ancListItems;
    @XmlAttribute(name = "isTemplate")
    protected Byte isTemplate;

    /**
     * Gets the value of the hdlTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdlTitle() {
        return hdlTitle;
    }

    /**
     * Sets the value of the hdlTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdlTitle(String value) {
        this.hdlTitle = value;
    }

    /**
     * Gets the value of the optRandom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptRandom() {
        return optRandom;
    }

    /**
     * Sets the value of the optRandom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptRandom(String value) {
        this.optRandom = value;
    }

    /**
     * Gets the value of the imgThumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgThumbnail() {
        return imgThumbnail;
    }

    /**
     * Sets the value of the imgThumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgThumbnail(String value) {
        this.imgThumbnail = value;
    }

    /**
     * Gets the value of the stfThumnailTeaserOnPageCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStfThumnailTeaserOnPageCaption() {
        return stfThumnailTeaserOnPageCaption;
    }

    /**
     * Sets the value of the stfThumnailTeaserOnPageCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStfThumnailTeaserOnPageCaption(String value) {
        this.stfThumnailTeaserOnPageCaption = value;
    }

    /**
     * Gets the value of the imgThumbnailTeaserOnPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgThumbnailTeaserOnPage() {
        return imgThumbnailTeaserOnPage;
    }

    /**
     * Sets the value of the imgThumbnailTeaserOnPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgThumbnailTeaserOnPage(String value) {
        this.imgThumbnailTeaserOnPage = value;
    }

    /**
     * Gets the value of the ancListItems property.
     * 
     * @return
     *     possible object is
     *     {@link AncListItemsType }
     *     
     */
    public AncListItemsType getAncListItems() {
        return ancListItems;
    }

    /**
     * Sets the value of the ancListItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link AncListItemsType }
     *     
     */
    public void setAncListItems(AncListItemsType value) {
        this.ancListItems = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsTemplate(Byte value) {
        this.isTemplate = value;
    }

}
