//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:40:13 PM EST 
//

package com.australia.cqimport.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for VideoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="VideoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="anc_Link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opt_BrightCovePlayerType" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="opt_isEmbeded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="opt_videoOption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_BrightcoveHeight" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="stf_BrightCoveWidth" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="stf_CaptionTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_LinkText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_MediaID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_TargetedCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stf_ViocorpHeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stf_ViocorpWidth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="txt_embedCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txt_VideoDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isTemplate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VideoType", propOrder = { "headline", "ancLink", "optBrightCovePlayerType", "optIsEmbeded",
	"optVideoOption", "stfBrightcoveHeight", "stfBrightCoveWidth", "stfCaptionTitle", "stfLinkText", "stfMediaID",
	"stfTargetedCountry", "stfViocorpHeight", "stfViocorpWidth", "txtEmbedCode", "txtVideoDescription" })
public class VideoType {

	protected String headline;
	@XmlElement(name = "anc_Link", required = true)
	protected String ancLink;
	@XmlElement(name = "opt_BrightCovePlayerType")
	protected Long optBrightCovePlayerType;
	@XmlElement(name = "opt_isEmbeded", required = true)
	protected String optIsEmbeded;
	@XmlElement(name = "opt_videoOption", required = true)
	protected String optVideoOption;
	@XmlElement(name = "stf_BrightcoveHeight")
	protected Short stfBrightcoveHeight;
	@XmlElement(name = "stf_BrightCoveWidth")
	protected Short stfBrightCoveWidth;
	@XmlElement(name = "stf_CaptionTitle", required = true)
	protected String stfCaptionTitle;
	@XmlElement(name = "stf_LinkText", required = true)
	protected String stfLinkText;
	@XmlElement(name = "stf_MediaID", required = true)
	protected String stfMediaID;
	@XmlElement(name = "stf_TargetedCountry", required = true)
	protected String stfTargetedCountry;
	@XmlElement(name = "stf_ViocorpHeight")
	protected String stfViocorpHeight;
	@XmlElement(name = "stf_ViocorpWidth")
	protected String stfViocorpWidth;
	@XmlElement(name = "txt_embedCode", required = true)
	protected String txtEmbedCode;
	@XmlElement(name = "txt_VideoDescription", required = true)
	protected String txtVideoDescription;
	@XmlAttribute(name = "isTemplate")
	protected Byte isTemplate;

	/**
	 * Gets the value of the headline property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeadline() {
		return headline;
	}

	/**
	 * Sets the value of the headline property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setHeadline(String value) {
		this.headline = value;
	}

	/**
	 * Gets the value of the ancLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAncLink() {
		return ancLink;
	}

	/**
	 * Sets the value of the ancLink property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAncLink(String value) {
		this.ancLink = value;
	}

	/**
	 * Gets the value of the optBrightCovePlayerType property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getOptBrightCovePlayerType() {
		return optBrightCovePlayerType;
	}

	/**
	 * Sets the value of the optBrightCovePlayerType property.
	 * 
	 * @param value allowed object is {@link Long }
	 * 
	 */
	public void setOptBrightCovePlayerType(Long value) {
		this.optBrightCovePlayerType = value;
	}

	/**
	 * Gets the value of the optIsEmbeded property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOptIsEmbeded() {
		return optIsEmbeded;
	}

	/**
	 * Sets the value of the optIsEmbeded property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOptIsEmbeded(String value) {
		this.optIsEmbeded = value;
	}

	/**
	 * Gets the value of the optVideoOption property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOptVideoOption() {
		return optVideoOption;
	}

	/**
	 * Sets the value of the optVideoOption property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOptVideoOption(String value) {
		this.optVideoOption = value;
	}

	/**
	 * Gets the value of the stfBrightcoveHeight property.
	 * 
	 * @return possible object is {@link Short }
	 * 
	 */
	public Short getStfBrightcoveHeight() {
		return stfBrightcoveHeight;
	}

	/**
	 * Sets the value of the stfBrightcoveHeight property.
	 * 
	 * @param value allowed object is {@link Short }
	 * 
	 */
	public void setStfBrightcoveHeight(Short value) {
		this.stfBrightcoveHeight = value;
	}

	/**
	 * Gets the value of the stfBrightCoveWidth property.
	 * 
	 * @return possible object is {@link Short }
	 * 
	 */
	public Short getStfBrightCoveWidth() {
		return stfBrightCoveWidth;
	}

	/**
	 * Sets the value of the stfBrightCoveWidth property.
	 * 
	 * @param value allowed object is {@link Short }
	 * 
	 */
	public void setStfBrightCoveWidth(Short value) {
		this.stfBrightCoveWidth = value;
	}

	/**
	 * Gets the value of the stfCaptionTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfCaptionTitle() {
		return stfCaptionTitle;
	}

	/**
	 * Sets the value of the stfCaptionTitle property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfCaptionTitle(String value) {
		this.stfCaptionTitle = value;
	}

	/**
	 * Gets the value of the stfLinkText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfLinkText() {
		return stfLinkText;
	}

	/**
	 * Sets the value of the stfLinkText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfLinkText(String value) {
		this.stfLinkText = value;
	}

	/**
	 * Gets the value of the stfMediaID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfMediaID() {
		return stfMediaID;
	}

	/**
	 * Sets the value of the stfMediaID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfMediaID(String value) {
		this.stfMediaID = value;
	}

	/**
	 * Gets the value of the stfTargetedCountry property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfTargetedCountry() {
		return stfTargetedCountry;
	}

	/**
	 * Sets the value of the stfTargetedCountry property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfTargetedCountry(String value) {
		this.stfTargetedCountry = value;
	}

	/**
	 * Gets the value of the stfViocorpHeight property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfViocorpHeight() {
		return stfViocorpHeight;
	}

	/**
	 * Sets the value of the stfViocorpHeight property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfViocorpHeight(String value) {
		this.stfViocorpHeight = value;
	}

	/**
	 * Gets the value of the stfViocorpWidth property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStfViocorpWidth() {
		return stfViocorpWidth;
	}

	/**
	 * Sets the value of the stfViocorpWidth property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStfViocorpWidth(String value) {
		this.stfViocorpWidth = value;
	}

	/**
	 * Gets the value of the txtEmbedCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTxtEmbedCode() {
		return txtEmbedCode;
	}

	/**
	 * Sets the value of the txtEmbedCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTxtEmbedCode(String value) {
		this.txtEmbedCode = value;
	}

	/**
	 * Gets the value of the txtVideoDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTxtVideoDescription() {
		return txtVideoDescription;
	}

	/**
	 * Sets the value of the txtVideoDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTxtVideoDescription(String value) {
		this.txtVideoDescription = value;
	}

	/**
	 * Gets the value of the isTemplate property.
	 * 
	 * @return possible object is {@link Byte }
	 * 
	 */
	public Byte getIsTemplate() {
		return isTemplate;
	}

	/**
	 * Sets the value of the isTemplate property.
	 * 
	 * @param value allowed object is {@link Byte }
	 * 
	 */
	public void setIsTemplate(Byte value) {
		this.isTemplate = value;
	}

}
