//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_attributeTypeRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_attributeTypeRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute_type_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_type_id_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_attributeTypeRowType")
public class ProductAttributeTypeRowType {

	@XmlElement(name = "attribute_type_id")
	protected String attributeTypeId;
	@XmlElement(name = "attribute_type_id_description")
	protected String attributeTypeIdDescription;
	@XmlElement(name = "attribute_id")
	protected String attributeId;
	@XmlElement(name = "attribute_id_description")
	protected String attributeIdDescription;

	/**
	 * Gets the value of the attributeTypeId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeTypeId() {
		return attributeTypeId;
	}

	/**
	 * Sets the value of the attributeTypeId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeTypeId(String value) {
		this.attributeTypeId = value;
	}

	/**
	 * Gets the value of the attributeTypeIdDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeTypeIdDescription() {
		return attributeTypeIdDescription;
	}

	/**
	 * Sets the value of the attributeTypeIdDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeTypeIdDescription(String value) {
		this.attributeTypeIdDescription = value;
	}

	/**
	 * Gets the value of the attributeId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeId() {
		return attributeId;
	}

	/**
	 * Sets the value of the attributeId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeId(String value) {
		this.attributeId = value;
	}

	/**
	 * Gets the value of the attributeIdDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdDescription() {
		return attributeIdDescription;
	}

	/**
	 * Sets the value of the attributeIdDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdDescription(String value) {
		this.attributeIdDescription = value;
	}

}
