//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_distributionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_distributionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="product_record" type="{}product_recordType"/>
 *         &lt;element name="event_frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_entry_cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_address" type="{}product_addressType"/>
 *         &lt;element name="product_attribute" type="{}product_attributeType"/>
 *         &lt;element name="product_award" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_brochure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_communication" type="{}product_communicationType"/>
 *         &lt;element name="product_contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_external_system" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_licence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_multimedia" type="{}product_multimediaType"/>
 *         &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_open_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_proximity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_rate_basis_comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_related_product" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_related_service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_season" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_session_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_site" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_sponsor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_vertical_classification" type="{}product_vertical_classificationType"/>
 *         &lt;element name="product_service" type="{}product_serviceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="product_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_distributionType")
public class ProductDistributionType {

	@XmlElement(name = "product_record")
	protected ProductRecordType productRecord;
	@XmlElement(name = "event_frequency")
	protected String eventFrequency;
	@XmlElement(name = "product_entry_cost")
	protected String productEntryCost;
	@XmlElement(name = "product_address")
	protected ProductAddressType productAddress;
	@XmlElement(name = "product_attribute")
	protected ProductAttributeType productAttribute;
	@XmlElement(name = "product_award")
	protected String productAward;
	@XmlElement(name = "product_brochure")
	protected String productBrochure;
	@XmlElement(name = "product_comment")
	protected String productComment;
	@XmlElement(name = "product_communication")
	protected ProductCommunicationType productCommunication;
	@XmlElement(name = "product_contact")
	protected String productContact;
	@XmlElement(name = "product_external_system")
	protected String productExternalSystem;
	@XmlElement(name = "product_licence")
	protected String productLicence;
	@XmlElement(name = "product_multimedia")
	protected ProductMultimediaType productMultimedia;
	@XmlElement(name = "product_name")
	protected String productName;
	@XmlElement(name = "product_open_time")
	protected String productOpenTime;
	@XmlElement(name = "product_proximity")
	protected String productProximity;
	@XmlElement(name = "product_rate_basis_comment")
	protected String productRateBasisComment;
	@XmlElement(name = "product_related_product")
	protected String productRelatedProduct;
	@XmlElement(name = "product_related_service")
	protected String productRelatedService;
	@XmlElement(name = "product_season")
	protected String productSeason;
	@XmlElement(name = "product_session_time")
	protected String productSessionTime;
	@XmlElement(name = "product_site")
	protected String productSite;
	@XmlElement(name = "product_sponsor")
	protected String productSponsor;
	@XmlElement(name = "product_vertical_classification")
	protected ProductVerticalClassificationType productVerticalClassification;
	@XmlElement(name = "product_service")
	protected ProductServiceType productService;
	@XmlAttribute(name = "product_id")
	protected Integer productId;

	/**
	 * Gets the value of the productRecord property.
	 * 
	 * @return possible object is {@link ProductRecordType }
	 * 
	 */
	public ProductRecordType getProductRecord() {
		return productRecord;
	}

	/**
	 * Sets the value of the productRecord property.
	 * 
	 * @param value allowed object is {@link ProductRecordType }
	 * 
	 */
	public void setProductRecord(ProductRecordType value) {
		this.productRecord = value;
	}

	/**
	 * Gets the value of the eventFrequency property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEventFrequency() {
		return eventFrequency;
	}

	/**
	 * Sets the value of the eventFrequency property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEventFrequency(String value) {
		this.eventFrequency = value;
	}

	/**
	 * Gets the value of the productEntryCost property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductEntryCost() {
		return productEntryCost;
	}

	/**
	 * Sets the value of the productEntryCost property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductEntryCost(String value) {
		this.productEntryCost = value;
	}

	/**
	 * Gets the value of the productAddress property.
	 * 
	 * @return possible object is {@link ProductAddressType }
	 * 
	 */
	public ProductAddressType getProductAddress() {
		return productAddress;
	}

	/**
	 * Sets the value of the productAddress property.
	 * 
	 * @param value allowed object is {@link ProductAddressType }
	 * 
	 */
	public void setProductAddress(ProductAddressType value) {
		this.productAddress = value;
	}

	/**
	 * Gets the value of the productAttribute property.
	 * 
	 * @return possible object is {@link ProductAttributeType }
	 * 
	 */
	public ProductAttributeType getProductAttribute() {
		return productAttribute;
	}

	/**
	 * Sets the value of the productAttribute property.
	 * 
	 * @param value allowed object is {@link ProductAttributeType }
	 * 
	 */
	public void setProductAttribute(ProductAttributeType value) {
		this.productAttribute = value;
	}

	/**
	 * Gets the value of the productAward property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductAward() {
		return productAward;
	}

	/**
	 * Sets the value of the productAward property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductAward(String value) {
		this.productAward = value;
	}

	/**
	 * Gets the value of the productBrochure property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductBrochure() {
		return productBrochure;
	}

	/**
	 * Sets the value of the productBrochure property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductBrochure(String value) {
		this.productBrochure = value;
	}

	/**
	 * Gets the value of the productComment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductComment() {
		return productComment;
	}

	/**
	 * Sets the value of the productComment property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductComment(String value) {
		this.productComment = value;
	}

	/**
	 * Gets the value of the productCommunication property.
	 * 
	 * @return possible object is {@link ProductCommunicationType }
	 * 
	 */
	public ProductCommunicationType getProductCommunication() {
		return productCommunication;
	}

	/**
	 * Sets the value of the productCommunication property.
	 * 
	 * @param value allowed object is {@link ProductCommunicationType }
	 * 
	 */
	public void setProductCommunication(ProductCommunicationType value) {
		this.productCommunication = value;
	}

	/**
	 * Gets the value of the productContact property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductContact() {
		return productContact;
	}

	/**
	 * Sets the value of the productContact property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductContact(String value) {
		this.productContact = value;
	}

	/**
	 * Gets the value of the productExternalSystem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductExternalSystem() {
		return productExternalSystem;
	}

	/**
	 * Sets the value of the productExternalSystem property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductExternalSystem(String value) {
		this.productExternalSystem = value;
	}

	/**
	 * Gets the value of the productLicence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductLicence() {
		return productLicence;
	}

	/**
	 * Sets the value of the productLicence property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductLicence(String value) {
		this.productLicence = value;
	}

	/**
	 * Gets the value of the productMultimedia property.
	 * 
	 * @return possible object is {@link ProductMultimediaType }
	 * 
	 */
	public ProductMultimediaType getProductMultimedia() {
		return productMultimedia;
	}

	/**
	 * Sets the value of the productMultimedia property.
	 * 
	 * @param value allowed object is {@link ProductMultimediaType }
	 * 
	 */
	public void setProductMultimedia(ProductMultimediaType value) {
		this.productMultimedia = value;
	}

	/**
	 * Gets the value of the productName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * Sets the value of the productName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductName(String value) {
		this.productName = value;
	}

	/**
	 * Gets the value of the productOpenTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductOpenTime() {
		return productOpenTime;
	}

	/**
	 * Sets the value of the productOpenTime property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductOpenTime(String value) {
		this.productOpenTime = value;
	}

	/**
	 * Gets the value of the productProximity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductProximity() {
		return productProximity;
	}

	/**
	 * Sets the value of the productProximity property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductProximity(String value) {
		this.productProximity = value;
	}

	/**
	 * Gets the value of the productRateBasisComment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductRateBasisComment() {
		return productRateBasisComment;
	}

	/**
	 * Sets the value of the productRateBasisComment property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductRateBasisComment(String value) {
		this.productRateBasisComment = value;
	}

	/**
	 * Gets the value of the productRelatedProduct property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductRelatedProduct() {
		return productRelatedProduct;
	}

	/**
	 * Sets the value of the productRelatedProduct property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductRelatedProduct(String value) {
		this.productRelatedProduct = value;
	}

	/**
	 * Gets the value of the productRelatedService property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductRelatedService() {
		return productRelatedService;
	}

	/**
	 * Sets the value of the productRelatedService property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductRelatedService(String value) {
		this.productRelatedService = value;
	}

	/**
	 * Gets the value of the productSeason property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductSeason() {
		return productSeason;
	}

	/**
	 * Sets the value of the productSeason property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductSeason(String value) {
		this.productSeason = value;
	}

	/**
	 * Gets the value of the productSessionTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductSessionTime() {
		return productSessionTime;
	}

	/**
	 * Sets the value of the productSessionTime property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductSessionTime(String value) {
		this.productSessionTime = value;
	}

	/**
	 * Gets the value of the productSite property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductSite() {
		return productSite;
	}

	/**
	 * Sets the value of the productSite property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductSite(String value) {
		this.productSite = value;
	}

	/**
	 * Gets the value of the productSponsor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductSponsor() {
		return productSponsor;
	}

	/**
	 * Sets the value of the productSponsor property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductSponsor(String value) {
		this.productSponsor = value;
	}

	/**
	 * Gets the value of the productVerticalClassification property.
	 * 
	 * @return possible object is {@link ProductVerticalClassificationType }
	 * 
	 */
	public ProductVerticalClassificationType getProductVerticalClassification() {
		return productVerticalClassification;
	}

	/**
	 * Sets the value of the productVerticalClassification property.
	 * 
	 * @param value allowed object is {@link ProductVerticalClassificationType }
	 * 
	 */
	public void setProductVerticalClassification(ProductVerticalClassificationType value) {
		this.productVerticalClassification = value;
	}

	/**
	 * Gets the value of the productService property.
	 * 
	 * @return possible object is {@link ProductServiceType }
	 * 
	 */
	public ProductServiceType getProductService() {
		return productService;
	}

	/**
	 * Sets the value of the productService property.
	 * 
	 * @param value allowed object is {@link ProductServiceType }
	 * 
	 */
	public void setProductService(ProductServiceType value) {
		this.productService = value;
	}

	/**
	 * Gets the value of the productId property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * Sets the value of the productId property.
	 * 
	 * @param value allowed object is {@link Integer }
	 * 
	 */
	public void setProductId(Integer value) {
		this.productId = value;
	}

}
