//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for product_recordType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_recordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="international_ready_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="national_head_office_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="product_category_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="owning_organisation_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contributing_organisation_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brochure_available_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="validity_date_from" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="validity_date_to" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="attribute_id_atdw_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_atdw_status_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="atdw_expiry_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="free_entry_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="attribute_id_currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_currency_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_rate_basis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_rate_basis_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rate_from" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="rate_to" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="city_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domestic_region_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domestic_region_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_category_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_recordType")
public class ProductRecordType {

	@XmlElement(name = "international_ready_flag")
	protected int internationalReadyFlag;
	@XmlElement(name = "national_head_office_flag")
	protected int nationalHeadOfficeFlag;
	@XmlElement(name = "product_category_id")
	protected String productCategoryId;
	@XmlElement(name = "owning_organisation_id")
	protected String owningOrganisationId;
	@XmlElement(name = "contributing_organisation_id")
	protected String contributingOrganisationId;
	@XmlElement(name = "product_name")
	protected String productName;
	@XmlElement(name = "brochure_available_flag")
	protected int brochureAvailableFlag;
	@XmlElement(name = "validity_date_from")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar validityDateFrom;
	@XmlElement(name = "validity_date_to")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar validityDateTo;
	@XmlElement(name = "attribute_id_atdw_status")
	protected String attributeIdAtdwStatus;
	@XmlElement(name = "attribute_id_atdw_status_description")
	protected String attributeIdAtdwStatusDescription;
	@XmlElement(name = "atdw_expiry_date")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar atdwExpiryDate;
	@XmlElement(name = "free_entry_flag")
	protected int freeEntryFlag;
	@XmlElement(name = "attribute_id_currency")
	protected String attributeIdCurrency;
	@XmlElement(name = "attribute_id_currency_description")
	protected String attributeIdCurrencyDescription;
	@XmlElement(name = "attribute_id_rate_basis")
	protected String attributeIdRateBasis;
	@XmlElement(name = "attribute_id_rate_basis_description")
	protected String attributeIdRateBasisDescription;
	@XmlElement(name = "rate_from")
	protected BigDecimal rateFrom;
	@XmlElement(name = "rate_to")
	protected BigDecimal rateTo;
	@XmlElement(name = "city_name")
	protected String cityName;
	@XmlElement(name = "area_name")
	protected String areaName;
	@XmlElement(name = "state_name")
	protected String stateName;
	@XmlElement(name = "country_name")
	protected String countryName;
	@XmlElement(name = "domestic_region_name")
	protected String domesticRegionName;
	@XmlElement(name = "domestic_region_code")
	protected String domesticRegionCode;
	@XmlElement(name = "product_category_description")
	protected String productCategoryDescription;
	@XmlElement(name = "product_description")
	protected String productDescription;

	/**
	 * Gets the value of the internationalReadyFlag property.
	 * 
	 */
	public int getInternationalReadyFlag() {
		return internationalReadyFlag;
	}

	/**
	 * Sets the value of the internationalReadyFlag property.
	 * 
	 */
	public void setInternationalReadyFlag(int value) {
		this.internationalReadyFlag = value;
	}

	/**
	 * Gets the value of the nationalHeadOfficeFlag property.
	 * 
	 */
	public int getNationalHeadOfficeFlag() {
		return nationalHeadOfficeFlag;
	}

	/**
	 * Sets the value of the nationalHeadOfficeFlag property.
	 * 
	 */
	public void setNationalHeadOfficeFlag(int value) {
		this.nationalHeadOfficeFlag = value;
	}

	/**
	 * Gets the value of the productCategoryId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductCategoryId() {
		return productCategoryId;
	}

	/**
	 * Sets the value of the productCategoryId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductCategoryId(String value) {
		this.productCategoryId = value;
	}

	/**
	 * Gets the value of the owningOrganisationId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOwningOrganisationId() {
		return owningOrganisationId;
	}

	/**
	 * Sets the value of the owningOrganisationId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOwningOrganisationId(String value) {
		this.owningOrganisationId = value;
	}

	/**
	 * Gets the value of the contributingOrganisationId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContributingOrganisationId() {
		return contributingOrganisationId;
	}

	/**
	 * Sets the value of the contributingOrganisationId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setContributingOrganisationId(String value) {
		this.contributingOrganisationId = value;
	}

	/**
	 * Gets the value of the productName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * Sets the value of the productName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductName(String value) {
		this.productName = value;
	}

	/**
	 * Gets the value of the brochureAvailableFlag property.
	 * 
	 */
	public int getBrochureAvailableFlag() {
		return brochureAvailableFlag;
	}

	/**
	 * Sets the value of the brochureAvailableFlag property.
	 * 
	 */
	public void setBrochureAvailableFlag(int value) {
		this.brochureAvailableFlag = value;
	}

	/**
	 * Gets the value of the validityDateFrom property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getValidityDateFrom() {
		return validityDateFrom;
	}

	/**
	 * Sets the value of the validityDateFrom property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setValidityDateFrom(XMLGregorianCalendar value) {
		this.validityDateFrom = value;
	}

	/**
	 * Gets the value of the validityDateTo property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getValidityDateTo() {
		return validityDateTo;
	}

	/**
	 * Sets the value of the validityDateTo property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setValidityDateTo(XMLGregorianCalendar value) {
		this.validityDateTo = value;
	}

	/**
	 * Gets the value of the attributeIdAtdwStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdAtdwStatus() {
		return attributeIdAtdwStatus;
	}

	/**
	 * Sets the value of the attributeIdAtdwStatus property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdAtdwStatus(String value) {
		this.attributeIdAtdwStatus = value;
	}

	/**
	 * Gets the value of the attributeIdAtdwStatusDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdAtdwStatusDescription() {
		return attributeIdAtdwStatusDescription;
	}

	/**
	 * Sets the value of the attributeIdAtdwStatusDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdAtdwStatusDescription(String value) {
		this.attributeIdAtdwStatusDescription = value;
	}

	/**
	 * Gets the value of the atdwExpiryDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAtdwExpiryDate() {
		return atdwExpiryDate;
	}

	/**
	 * Sets the value of the atdwExpiryDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAtdwExpiryDate(XMLGregorianCalendar value) {
		this.atdwExpiryDate = value;
	}

	/**
	 * Gets the value of the freeEntryFlag property.
	 * 
	 */
	public int getFreeEntryFlag() {
		return freeEntryFlag;
	}

	/**
	 * Sets the value of the freeEntryFlag property.
	 * 
	 */
	public void setFreeEntryFlag(int value) {
		this.freeEntryFlag = value;
	}

	/**
	 * Gets the value of the attributeIdCurrency property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdCurrency() {
		return attributeIdCurrency;
	}

	/**
	 * Sets the value of the attributeIdCurrency property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdCurrency(String value) {
		this.attributeIdCurrency = value;
	}

	/**
	 * Gets the value of the attributeIdCurrencyDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdCurrencyDescription() {
		return attributeIdCurrencyDescription;
	}

	/**
	 * Sets the value of the attributeIdCurrencyDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdCurrencyDescription(String value) {
		this.attributeIdCurrencyDescription = value;
	}

	/**
	 * Gets the value of the attributeIdRateBasis property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdRateBasis() {
		return attributeIdRateBasis;
	}

	/**
	 * Sets the value of the attributeIdRateBasis property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdRateBasis(String value) {
		this.attributeIdRateBasis = value;
	}

	/**
	 * Gets the value of the attributeIdRateBasisDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdRateBasisDescription() {
		return attributeIdRateBasisDescription;
	}

	/**
	 * Sets the value of the attributeIdRateBasisDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdRateBasisDescription(String value) {
		this.attributeIdRateBasisDescription = value;
	}

	/**
	 * Gets the value of the rateFrom property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getRateFrom() {
		return rateFrom;
	}

	/**
	 * Sets the value of the rateFrom property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setRateFrom(BigDecimal value) {
		this.rateFrom = value;
	}

	/**
	 * Gets the value of the rateTo property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getRateTo() {
		return rateTo;
	}

	/**
	 * Sets the value of the rateTo property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setRateTo(BigDecimal value) {
		this.rateTo = value;
	}

	/**
	 * Gets the value of the cityName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * Sets the value of the cityName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAreaName(String value) {
		this.areaName = value;
	}

	/**
	 * Gets the value of the stateName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * Sets the value of the cityName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCityName(String value) {
		this.cityName = value;
	}

	/**
	 * Gets the value of the stateName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStateName() {
		return stateName;
	}

	/**
	 * Sets the value of the stateName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStateName(String value) {
		this.stateName = value;
	}

	/**
	 * Gets the value of the countryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * Sets the value of the countryName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCountryName(String value) {
		this.countryName = value;
	}

	/**
	 * Gets the value of the domesticRegionName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomesticRegionName() {
		return domesticRegionName;
	}

	/**
	 * Sets the value of the domesticRegionName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDomesticRegionName(String value) {
		this.domesticRegionName = value;
	}

	/**
	 * Gets the value of the domesticRegionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomesticRegionCode() {
		return domesticRegionCode;
	}

	/**
	 * Sets the value of the domesticRegionCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDomesticRegionCode(String value) {
		this.domesticRegionCode = value;
	}

	/**
	 * Gets the value of the productCategoryDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductCategoryDescription() {
		return productCategoryDescription;
	}

	/**
	 * Sets the value of the productCategoryDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductCategoryDescription(String value) {
		this.productCategoryDescription = value;
	}

	/**
	 * Gets the value of the productDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductDescription() {
		return productDescription;
	}

	/**
	 * Sets the value of the productDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductDescription(String value) {
		this.productDescription = value;
	}

}
