//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_address_domestic_region_relationshipRowType complex
 * type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_address_domestic_region_relationshipRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domestic_region_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domestic_region_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domestic_region_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_address_domestic_region_relationshipRowType")
public class ProductAddressDomesticRegionRelationshipRowType {

	@XmlElement(name = "domestic_region_name")
	protected String domesticRegionName;
	@XmlElement(name = "domestic_region_code")
	protected String domesticRegionCode;
	@XmlElement(name = "domestic_region_type")
	protected String domesticRegionType;

	/**
	 * Gets the value of the domesticRegionName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomesticRegionName() {
		return domesticRegionName;
	}

	/**
	 * Sets the value of the domesticRegionName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDomesticRegionName(String value) {
		this.domesticRegionName = value;
	}

	/**
	 * Gets the value of the domesticRegionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomesticRegionCode() {
		return domesticRegionCode;
	}

	/**
	 * Sets the value of the domesticRegionCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDomesticRegionCode(String value) {
		this.domesticRegionCode = value;
	}

	/**
	 * Gets the value of the domesticRegionType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomesticRegionType() {
		return domesticRegionType;
	}

	/**
	 * Sets the value of the domesticRegionType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDomesticRegionType(String value) {
		this.domesticRegionType = value;
	}

}
