//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_communicationTypeRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_communicationTypeRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute_id_communication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_communication_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="communication_isd_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="communication_detail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_communicationTypeRowType")
public class ProductCommunicationTypeRowType {

	@XmlElement(name = "attribute_id_communication")
	protected String attributeIdCommunication;
	@XmlElement(name = "attribute_id_communication_description")
	protected String attributeIdCommunicationDescription;
	@XmlElement(name = "communication_isd_code")
	protected int communicationIsdCode;
	@XmlElement(name = "country_name")
	protected String countryName;
	@XmlElement(name = "communication_detail")
	protected String communicationDetail;

	/**
	 * Gets the value of the attributeIdCommunication property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdCommunication() {
		return attributeIdCommunication;
	}

	/**
	 * Sets the value of the attributeIdCommunication property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdCommunication(String value) {
		this.attributeIdCommunication = value;
	}

	/**
	 * Gets the value of the attributeIdCommunicationDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdCommunicationDescription() {
		return attributeIdCommunicationDescription;
	}

	/**
	 * Sets the value of the attributeIdCommunicationDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdCommunicationDescription(String value) {
		this.attributeIdCommunicationDescription = value;
	}

	/**
	 * Gets the value of the communicationIsdCode property.
	 * 
	 */
	public int getCommunicationIsdCode() {
		return communicationIsdCode;
	}

	/**
	 * Sets the value of the communicationIsdCode property.
	 * 
	 */
	public void setCommunicationIsdCode(int value) {
		this.communicationIsdCode = value;
	}

	/**
	 * Gets the value of the countryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * Sets the value of the countryName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCountryName(String value) {
		this.countryName = value;
	}

	/**
	 * Gets the value of the communicationDetail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCommunicationDetail() {
		return communicationDetail;
	}

	/**
	 * Sets the value of the communicationDetail property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCommunicationDetail(String value) {
		this.communicationDetail = value;
	}

}
