//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_vertical_classificationTypeRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_vertical_classificationTypeRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="product_type_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_type_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_sub_type_lowest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_vertical_classificationTypeRowType")
public class ProductVerticalClassificationTypeRowType {

	@XmlElement(name = "product_type_id")
	protected String productTypeId;
	@XmlElement(name = "product_type_description")
	protected String productTypeDescription;
	@XmlElement(name = "product_sub_type_lowest")
	protected String productSubTypeLowest;

	/**
	 * Gets the value of the productTypeId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductTypeId() {
		return productTypeId;
	}

	/**
	 * Sets the value of the productTypeId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductTypeId(String value) {
		this.productTypeId = value;
	}

	/**
	 * Gets the value of the productTypeDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductTypeDescription() {
		return productTypeDescription;
	}

	/**
	 * Sets the value of the productTypeDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductTypeDescription(String value) {
		this.productTypeDescription = value;
	}

	/**
	 * Gets the value of the productSubTypeLowest property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductSubTypeLowest() {
		return productSubTypeLowest;
	}

	/**
	 * Sets the value of the productSubTypeLowest property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductSubTypeLowest(String value) {
		this.productSubTypeLowest = value;
	}

}
