//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product_addressTypeRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_addressTypeRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute_id_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_address_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address_line_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="area_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address_postal_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="override_domestic_region_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="geocode_gda_latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="geocode_gda_longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="product_address_street_directory_relationship" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product_address_domestic_region_relationship" type="{}product_address_domestic_region_relationshipType"/>
 *         &lt;element name="product_address_area_relationship" type="{}product_address_area_relationshipType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_addressTypeRowType")
public class ProductAddressTypeRowType {

	@XmlElement(name = "attribute_id_address")
	protected String attributeIdAddress;
	@XmlElement(name = "attribute_id_address_description")
	protected String attributeIdAddressDescription;
	@XmlElement(name = "address_line_1")
	protected String addressLine1;
	@XmlElement(name = "city_name")
	protected String cityName;
	@XmlElement(name = "area_name")
	protected String areaName;
	@XmlElement(name = "state_name")
	protected String stateName;
	@XmlElement(name = "country_name")
	protected String countryName;
	@XmlElement(name = "address_postal_code")
	protected int addressPostalCode;
	@XmlElement(name = "override_domestic_region_flag")
	protected int overrideDomesticRegionFlag;
	@XmlElement(name = "geocode_gda_latitude")
	protected BigDecimal geocodeGdaLatitude;
	@XmlElement(name = "geocode_gda_longitude")
	protected BigDecimal geocodeGdaLongitude;
	@XmlElement(name = "product_address_street_directory_relationship")
	protected String productAddressStreetDirectoryRelationship;
	@XmlElement(name = "product_address_domestic_region_relationship")
	protected ProductAddressDomesticRegionRelationshipType productAddressDomesticRegionRelationship;
	@XmlElement(name = "product_address_area_relationship")
	protected ProductAddressAreaRelationshipType productAddressAreaRelationship;

	/**
	 * Gets the value of the attributeIdAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdAddress() {
		return attributeIdAddress;
	}

	/**
	 * Sets the value of the attributeIdAddress property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdAddress(String value) {
		this.attributeIdAddress = value;
	}

	/**
	 * Gets the value of the attributeIdAddressDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdAddressDescription() {
		return attributeIdAddressDescription;
	}

	/**
	 * Sets the value of the attributeIdAddressDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdAddressDescription(String value) {
		this.attributeIdAddressDescription = value;
	}

	/**
	 * Gets the value of the addressLine1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddressLine1() {
		return addressLine1;
	}

	/**
	 * Sets the value of the addressLine1 property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAddressLine1(String value) {
		this.addressLine1 = value;
	}

	/**
	 * Gets the value of the cityName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * Sets the value of the cityName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCityName(String value) {
		this.cityName = value;
	}

	/**
	 * Gets the value of the areaName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * Sets the value of the areaName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAreaName(String value) {
		this.areaName = value;
	}

	/**
	 * Gets the value of the stateName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStateName() {
		return stateName;
	}

	/**
	 * Sets the value of the stateName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStateName(String value) {
		this.stateName = value;
	}

	/**
	 * Gets the value of the countryName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountryName() {
		return countryName;
	}

	/**
	 * Sets the value of the countryName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCountryName(String value) {
		this.countryName = value;
	}

	/**
	 * Gets the value of the addressPostalCode property.
	 * 
	 */
	public int getAddressPostalCode() {
		return addressPostalCode;
	}

	/**
	 * Sets the value of the addressPostalCode property.
	 * 
	 */
	public void setAddressPostalCode(int value) {
		this.addressPostalCode = value;
	}

	/**
	 * Gets the value of the overrideDomesticRegionFlag property.
	 * 
	 */
	public int getOverrideDomesticRegionFlag() {
		return overrideDomesticRegionFlag;
	}

	/**
	 * Sets the value of the overrideDomesticRegionFlag property.
	 * 
	 */
	public void setOverrideDomesticRegionFlag(int value) {
		this.overrideDomesticRegionFlag = value;
	}

	/**
	 * Gets the value of the geocodeGdaLatitude property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getGeocodeGdaLatitude() {
		return geocodeGdaLatitude;
	}

	/**
	 * Sets the value of the geocodeGdaLatitude property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setGeocodeGdaLatitude(BigDecimal value) {
		this.geocodeGdaLatitude = value;
	}

	/**
	 * Gets the value of the geocodeGdaLongitude property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getGeocodeGdaLongitude() {
		return geocodeGdaLongitude;
	}

	/**
	 * Sets the value of the geocodeGdaLongitude property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setGeocodeGdaLongitude(BigDecimal value) {
		this.geocodeGdaLongitude = value;
	}

	/**
	 * Gets the value of the productAddressStreetDirectoryRelationship property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductAddressStreetDirectoryRelationship() {
		return productAddressStreetDirectoryRelationship;
	}

	/**
	 * Sets the value of the productAddressStreetDirectoryRelationship property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setProductAddressStreetDirectoryRelationship(String value) {
		this.productAddressStreetDirectoryRelationship = value;
	}

	/**
	 * Gets the value of the productAddressDomesticRegionRelationship property.
	 * 
	 * @return possible object is
	 *         {@link ProductAddressDomesticRegionRelationshipType }
	 * 
	 */
	public ProductAddressDomesticRegionRelationshipType getProductAddressDomesticRegionRelationship() {
		return productAddressDomesticRegionRelationship;
	}

	/**
	 * Sets the value of the productAddressDomesticRegionRelationship property.
	 * 
	 * @param value allowed object is
	 *            {@link ProductAddressDomesticRegionRelationshipType }
	 * 
	 */
	public void setProductAddressDomesticRegionRelationship(ProductAddressDomesticRegionRelationshipType value) {
		this.productAddressDomesticRegionRelationship = value;
	}

	/**
	 * Gets the value of the productAddressAreaRelationship property.
	 * 
	 * @return possible object is {@link ProductAddressAreaRelationshipType }
	 * 
	 */
	public ProductAddressAreaRelationshipType getProductAddressAreaRelationship() {
		return productAddressAreaRelationship;
	}

	/**
	 * Sets the value of the productAddressAreaRelationship property.
	 * 
	 * @param value allowed object is {@link ProductAddressAreaRelationshipType }
	 * 
	 */
	public void setProductAddressAreaRelationship(ProductAddressAreaRelationshipType value) {
		this.productAddressAreaRelationship = value;
	}

}
