//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 10:44:38 AM EST 
//

package com.australia.atdw.remote.domain.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for product_multimediaTypeRowType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product_multimediaTypeRowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="market_variant_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="multimedia_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="authored_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="server_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_multimedia_file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_multimedia_file_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_multimedia_content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_multimedia_content_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_size_orientation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attribute_id_size_orientation_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="alt_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sequence_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product_multimediaTypeRowType")
public class ProductMultimediaTypeRowType {

	@XmlElement(name = "market_variant_id")
	protected String marketVariantId;
	@XmlElement(name = "multimedia_id")
	protected int multimediaId;
	@XmlElement(name = "authored_date")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar authoredDate;
	@XmlElement(name = "server_path")
	protected String serverPath;
	@XmlElement(name = "attribute_id_multimedia_file")
	protected String attributeIdMultimediaFile;
	@XmlElement(name = "attribute_id_multimedia_file_description")
	protected String attributeIdMultimediaFileDescription;
	@XmlElement(name = "attribute_id_multimedia_content")
	protected String attributeIdMultimediaContent;
	@XmlElement(name = "attribute_id_multimedia_content_description")
	protected String attributeIdMultimediaContentDescription;
	@XmlElement(name = "attribute_id_size_orientation")
	protected String attributeIdSizeOrientation;
	@XmlElement(name = "attribute_id_size_orientation_description")
	protected String attributeIdSizeOrientationDescription;
	protected int width;
	protected int height;
	@XmlElement(name = "alt_text")
	protected String altText;
	@XmlElement(name = "sequence_number")
	protected int sequenceNumber;

	/**
	 * Gets the value of the marketVariantId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarketVariantId() {
		return marketVariantId;
	}

	/**
	 * Sets the value of the marketVariantId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMarketVariantId(String value) {
		this.marketVariantId = value;
	}

	/**
	 * Gets the value of the multimediaId property.
	 * 
	 */
	public int getMultimediaId() {
		return multimediaId;
	}

	/**
	 * Sets the value of the multimediaId property.
	 * 
	 */
	public void setMultimediaId(int value) {
		this.multimediaId = value;
	}

	/**
	 * Gets the value of the authoredDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAuthoredDate() {
		return authoredDate;
	}

	/**
	 * Sets the value of the authoredDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAuthoredDate(XMLGregorianCalendar value) {
		this.authoredDate = value;
	}

	/**
	 * Gets the value of the serverPath property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServerPath() {
		return serverPath;
	}

	/**
	 * Sets the value of the serverPath property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setServerPath(String value) {
		this.serverPath = value;
	}

	/**
	 * Gets the value of the attributeIdMultimediaFile property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdMultimediaFile() {
		return attributeIdMultimediaFile;
	}

	/**
	 * Sets the value of the attributeIdMultimediaFile property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdMultimediaFile(String value) {
		this.attributeIdMultimediaFile = value;
	}

	/**
	 * Gets the value of the attributeIdMultimediaFileDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdMultimediaFileDescription() {
		return attributeIdMultimediaFileDescription;
	}

	/**
	 * Sets the value of the attributeIdMultimediaFileDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdMultimediaFileDescription(String value) {
		this.attributeIdMultimediaFileDescription = value;
	}

	/**
	 * Gets the value of the attributeIdMultimediaContent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdMultimediaContent() {
		return attributeIdMultimediaContent;
	}

	/**
	 * Sets the value of the attributeIdMultimediaContent property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdMultimediaContent(String value) {
		this.attributeIdMultimediaContent = value;
	}

	/**
	 * Gets the value of the attributeIdMultimediaContentDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdMultimediaContentDescription() {
		return attributeIdMultimediaContentDescription;
	}

	/**
	 * Sets the value of the attributeIdMultimediaContentDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdMultimediaContentDescription(String value) {
		this.attributeIdMultimediaContentDescription = value;
	}

	/**
	 * Gets the value of the attributeIdSizeOrientation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdSizeOrientation() {
		return attributeIdSizeOrientation;
	}

	/**
	 * Sets the value of the attributeIdSizeOrientation property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdSizeOrientation(String value) {
		this.attributeIdSizeOrientation = value;
	}

	/**
	 * Gets the value of the attributeIdSizeOrientationDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeIdSizeOrientationDescription() {
		return attributeIdSizeOrientationDescription;
	}

	/**
	 * Sets the value of the attributeIdSizeOrientationDescription property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAttributeIdSizeOrientationDescription(String value) {
		this.attributeIdSizeOrientationDescription = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 */
	public int getWidth() {
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 */
	public void setWidth(int value) {
		this.width = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 */
	public int getHeight() {
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 */
	public void setHeight(int value) {
		this.height = value;
	}

	/**
	 * Gets the value of the altText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAltText() {
		return altText;
	}

	/**
	 * Sets the value of the altText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAltText(String value) {
		this.altText = value;
	}

	/**
	 * Gets the value of the sequenceNumber property.
	 * 
	 */
	public int getSequenceNumber() {
		return sequenceNumber;
	}

	/**
	 * Sets the value of the sequenceNumber property.
	 * 
	 */
	public void setSequenceNumber(int value) {
		this.sequenceNumber = value;
	}

}
