//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.26 at 10:24:01 AM EST 
//

package com.australia.atdw.domain.products;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.australia.atdw.domain package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _AtdwSearchResponse_QNAME = new QName("", "atdw_search_response");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.australia.atdw.domain
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link AtdwProductsResponse }
	 * 
	 */
	public AtdwProductsResponse createAtdwSearchResponseType() {
		return new AtdwProductsResponse();
	}

	/**
	 * Create an instance of {@link Product }
	 * 
	 */
	public Product createProductRecordType() {
		return new Product();
	}

	/**
	 * Create an instance of {@link Products }
	 * 
	 */
	public Products createProductsType() {
		return new Products();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link AtdwProductsResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "atdw_search_response")
	public JAXBElement<AtdwProductsResponse> createAtdwSearchResponse(AtdwProductsResponse value) {
		return new JAXBElement<AtdwProductsResponse>(_AtdwSearchResponse_QNAME, AtdwProductsResponse.class, null, value);
	}

}
